---
services:
  app: &app_env
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 127.0.0.1:8080:8080
    environment:
      IS_DOCKER: '1'
      FLASK_APP: hushline
      FLASK_ENV: development
      ENCRYPTION_KEY: bi5FDwhZGKfc4urLJ_ChGtIAaOPgxd3RDOhnvct10mw=
      SECRET_KEY: cb3f4afde364bfb3956b97ca22ef4d2b593d9d980a4330686267cabcd2c0befd
      SESSION_FERNET_KEY: jY0gDbATEOQolx2SGj46YnkkbN6HQBB4YCABzwl1H1A=
      SQLALCHEMY_DATABASE_URI: postgresql://hushline:hushline@postgres:5432/hushline
      REGISTRATION_CODES_REQUIRED: 'false'
      ALIAS_MODE: always
      FIELDS_MODE: premium
      SESSION_COOKIE_NAME: session
      NOTIFICATIONS_ADDRESS: notifications@hushline.app
      DIRECTORY_VERIFIED_TAB_ENABLED: "${DIRECTORY_VERIFIED_TAB_ENABLED:-true}"
      SMTP_FORWARDING_MESSAGE_HTML: |
        ✊ Email forwarding is powered by
        <a href="https://riseup.net" target="_blank">Riseup.net</a>.
      BLOB_STORAGE_PUBLIC_DRIVER: s3
      BLOB_STORAGE_PUBLIC_S3_BUCKET: public
      BLOB_STORAGE_PUBLIC_S3_REGION: us-east-1  # from localstack defaults
      BLOB_STORAGE_PUBLIC_S3_ENDPOINT: "http://blob-storage:4566/"
      BLOB_STORAGE_PUBLIC_S3_CDN_ENDPOINT: "http://localhost:4566/public/"
      BLOB_STORAGE_PUBLIC_S3_ACCESS_KEY: "test"  # from localstack defaults
      BLOB_STORAGE_PUBLIC_S3_SECRET_KEY: "test"  # from localstack defaults
    volumes:
      - ./:/app
    depends_on:
      - postgres
      - blob-storage
    restart: always

  dev_data:
    <<: *app_env
    ports: []
    restart: on-failure
    command: make dev-data
    depends_on:
      - postgres

  postgres:
    image: postgres:16.4-alpine3.20
    environment:
      POSTGRES_USER: hushline
      POSTGRES_PASSWORD: hushline
      POSTGRES_DB: hushline
    ports:
      - 127.0.0.1:5432:5432

  blob-storage:
    image: localstack/localstack:latest
    environment:
      SERVICES: s3
      EDGE_PORT: "4566"
      HOSTNAME: blob-storage
      HOSTNAME_EXTERNAL: localhost:4566
      START_WEB: "0"
      SKIP_INFRA_DOWNLOADS: "true"
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4571:4571"
